name: "Chart - Release - PR"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please - ${{ matrix.group.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group:
          - name: Alpha Chart
            description: The unreleased charts available to devs from the GitHub OCI repo.
            config-file: .github/config/release-please/alpha/release-please-config.json
            manifest-file: .github/config/release-please/alpha/.release-please-manifest.json
            prefix: alpha
          - name: Stable Charts
            description: The released charts available to users from the main Helm repo.
            config-file: .github/config/release-please/release-please-config.json
            manifest-file: .github/config/release-please/.release-please-manifest.json
            prefix: stable
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        env:
          RELEASE_PLEASE_BRANCH_PREFIX: ${{ matrix.group.prefix }}
        with:
          token: '${{ secrets.RELEASE_PLEASE_TOKEN }}'
          # Config docs: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
          config-file: "${{ matrix.group.config-file }}"
          manifest-file: "${{ matrix.group.manifest-file }}"
